/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HackathonMatchRouteImport } from './routes/hackathon-match'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCounselorRouteImport } from './routes/_authenticated/counselor'
import { Route as AuthenticatedGameRouteImport } from './routes/_authenticated/game'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedManualRouteImport } from './routes/_authenticated/manual'
import { Route as AuthenticatedMatchRouteImport } from './routes/_authenticated/match'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as InviteTokenRouteImport } from './routes/invite_.$token'
import { Route as AuthenticatedCounselorThreadIdRouteImport } from './routes/_authenticated/counselor_.$threadId'
import { Route as AuthenticatedMatch1v1RouteImport } from './routes/_authenticated/match/1v1'
import { Route as AuthenticatedMatchMatchIdRouteImport } from './routes/_authenticated/match_.$matchId'
import { Route as AuthenticatedTestsTestIdRouteImport } from './routes/_authenticated/tests_.$testId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonMatchRoute = HackathonMatchRouteImport.update({
  id: '/hackathon-match',
  path: '/hackathon-match',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCounselorRoute = AuthenticatedCounselorRouteImport.update({
  id: '/counselor',
  path: '/counselor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGameRoute = AuthenticatedGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManualRoute = AuthenticatedManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchRoute = AuthenticatedMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite_/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCounselorThreadIdRoute =
  AuthenticatedCounselorThreadIdRouteImport.update({
    id: '/counselor_/$threadId',
    path: '/counselor/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatch1v1Route = AuthenticatedMatch1v1RouteImport.update({
  id: '/1v1',
  path: '/1v1',
  getParentRoute: () => AuthenticatedMatchRoute,
} as any)
const AuthenticatedMatchMatchIdRoute =
  AuthenticatedMatchMatchIdRouteImport.update({
    id: '/match_/$matchId',
    path: '/match/$matchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestsTestIdRoute =
  AuthenticatedTestsTestIdRouteImport.update({
    id: '/tests_/$testId',
    path: '/tests/$testId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hackathon-match': typeof HackathonMatchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/counselor': typeof AuthenticatedCounselorRoute
  '/game': typeof AuthenticatedGameRoute
  '/home': typeof AuthenticatedHomeRoute
  '/manual': typeof AuthenticatedManualRoute
  '/match': typeof AuthenticatedMatchRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/chat': typeof ApiChatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/counselor/$threadId': typeof AuthenticatedCounselorThreadIdRoute
  '/match/1v1': typeof AuthenticatedMatch1v1Route
  '/match/$matchId': typeof AuthenticatedMatchMatchIdRoute
  '/tests/$testId': typeof AuthenticatedTestsTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hackathon-match': typeof HackathonMatchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/counselor': typeof AuthenticatedCounselorRoute
  '/game': typeof AuthenticatedGameRoute
  '/home': typeof AuthenticatedHomeRoute
  '/manual': typeof AuthenticatedManualRoute
  '/match': typeof AuthenticatedMatchRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/chat': typeof ApiChatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/counselor/$threadId': typeof AuthenticatedCounselorThreadIdRoute
  '/match/1v1': typeof AuthenticatedMatch1v1Route
  '/match/$matchId': typeof AuthenticatedMatchMatchIdRoute
  '/tests/$testId': typeof AuthenticatedTestsTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/hackathon-match': typeof HackathonMatchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/counselor': typeof AuthenticatedCounselorRoute
  '/_authenticated/game': typeof AuthenticatedGameRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/manual': typeof AuthenticatedManualRoute
  '/_authenticated/match': typeof AuthenticatedMatchRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/api/chat': typeof ApiChatRoute
  '/invite_/$token': typeof InviteTokenRoute
  '/_authenticated/counselor_/$threadId': typeof AuthenticatedCounselorThreadIdRoute
  '/_authenticated/match/1v1': typeof AuthenticatedMatch1v1Route
  '/_authenticated/match_/$matchId': typeof AuthenticatedMatchMatchIdRoute
  '/_authenticated/tests_/$testId': typeof AuthenticatedTestsTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/hackathon-match'
    | '/reset-password'
    | '/counselor'
    | '/game'
    | '/home'
    | '/manual'
    | '/match'
    | '/onboarding'
    | '/profile'
    | '/api/chat'
    | '/invite/$token'
    | '/counselor/$threadId'
    | '/match/1v1'
    | '/match/$matchId'
    | '/tests/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/hackathon-match'
    | '/reset-password'
    | '/counselor'
    | '/game'
    | '/home'
    | '/manual'
    | '/match'
    | '/onboarding'
    | '/profile'
    | '/api/chat'
    | '/invite/$token'
    | '/counselor/$threadId'
    | '/match/1v1'
    | '/match/$matchId'
    | '/tests/$testId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/hackathon-match'
    | '/reset-password'
    | '/_authenticated/counselor'
    | '/_authenticated/game'
    | '/_authenticated/home'
    | '/_authenticated/manual'
    | '/_authenticated/match'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/api/chat'
    | '/invite_/$token'
    | '/_authenticated/counselor_/$threadId'
    | '/_authenticated/match/1v1'
    | '/_authenticated/match_/$matchId'
    | '/_authenticated/tests_/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HackathonMatchRoute: typeof HackathonMatchRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathon-match': {
      id: '/hackathon-match'
      path: '/hackathon-match'
      fullPath: '/hackathon-match'
      preLoaderRoute: typeof HackathonMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/counselor': {
      id: '/_authenticated/counselor'
      path: '/counselor'
      fullPath: '/counselor'
      preLoaderRoute: typeof AuthenticatedCounselorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/game': {
      id: '/_authenticated/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof AuthenticatedGameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manual': {
      id: '/_authenticated/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof AuthenticatedManualRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/match': {
      id: '/_authenticated/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof AuthenticatedMatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite_/$token': {
      id: '/invite_/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/counselor_/$threadId': {
      id: '/_authenticated/counselor_/$threadId'
      path: '/counselor/$threadId'
      fullPath: '/counselor/$threadId'
      preLoaderRoute: typeof AuthenticatedCounselorThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/match/1v1': {
      id: '/_authenticated/match/1v1'
      path: '/1v1'
      fullPath: '/match/1v1'
      preLoaderRoute: typeof AuthenticatedMatch1v1RouteImport
      parentRoute: typeof AuthenticatedMatchRoute
    }
    '/_authenticated/match_/$matchId': {
      id: '/_authenticated/match_/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof AuthenticatedMatchMatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests_/$testId': {
      id: '/_authenticated/tests_/$testId'
      path: '/tests/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof AuthenticatedTestsTestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedMatchRouteChildren {
  AuthenticatedMatch1v1Route: typeof AuthenticatedMatch1v1Route
}

const AuthenticatedMatchRouteChildren: AuthenticatedMatchRouteChildren = {
  AuthenticatedMatch1v1Route: AuthenticatedMatch1v1Route,
}

const AuthenticatedMatchRouteWithChildren =
  AuthenticatedMatchRoute._addFileChildren(AuthenticatedMatchRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCounselorRoute: typeof AuthenticatedCounselorRoute
  AuthenticatedGameRoute: typeof AuthenticatedGameRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedManualRoute: typeof AuthenticatedManualRoute
  AuthenticatedMatchRoute: typeof AuthenticatedMatchRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedCounselorThreadIdRoute: typeof AuthenticatedCounselorThreadIdRoute
  AuthenticatedMatchMatchIdRoute: typeof AuthenticatedMatchMatchIdRoute
  AuthenticatedTestsTestIdRoute: typeof AuthenticatedTestsTestIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCounselorRoute: AuthenticatedCounselorRoute,
  AuthenticatedGameRoute: AuthenticatedGameRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedManualRoute: AuthenticatedManualRoute,
  AuthenticatedMatchRoute: AuthenticatedMatchRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedCounselorThreadIdRoute: AuthenticatedCounselorThreadIdRoute,
  AuthenticatedMatchMatchIdRoute: AuthenticatedMatchMatchIdRoute,
  AuthenticatedTestsTestIdRoute: AuthenticatedTestsTestIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HackathonMatchRoute: HackathonMatchRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
